
export default {
    "web19201": {
      "opacity": 1,
      "position": "relative",
      "backgroundColor": "rgba(255, 255, 255, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 1920,
      "height": 5282,
      "left": 0,
      "top": 0
    },
  
    "web19201_rectangle108": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 1920,
      "height": 1025,
      "left": 0,
      "top": 3175
    },
    "web19201_rectangle81": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 1920,
      "height": 1022,
      "left": -1,
      "top": 0
    },
    "web19201_rectangle82": {
      "opacity": 0.4424700140953064,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 1920,
      "height": 1022,
      "left": -1,
      "top": 0
    },
    "web19201_rectangle97": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(54, 84, 124, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopWidth": 1,
      "borderTopColor": "rgba(112, 112, 112, 1)",
      "borderRightWidth": 1,
      "borderRightColor": "rgba(112, 112, 112, 1)",
      "borderBottomWidth": 1,
      "borderBottomColor": "rgba(112, 112, 112, 1)",
      "borderLeftWidth": 1,
      "borderLeftColor": "rgba(112, 112, 112, 1)",
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 35,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 35,
      "width": 106,
      "height": 59,
      "left": 0,
      "top": 0
    },
    "web19201_freedomToChooseTheHomeYouLove": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 76,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 1480,
      "height": 93,
      "left": 219,
      "top": 399
    },
    "web19201_withALenderWhoCares": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 76,
      "fontWeight": "700",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 938,
      "height": 93,
      "left": 490,
      "top": 492
    },
    "web19201_line9": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 1591,
      "height": 3,
      "left": 163.5,
      "top": 382
    },
    "web19201_careers": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 20,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 74,
      "height": 24,
      "left": 1698,
      "top": 18
    },
    "web19201_contact": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 20,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 78,
      "height": 24,
      "left": 1468,
      "top": 18
    },
    "web19201_locations": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 20,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 94,
      "height": 24,
      "left": 1575,
      "top": 18
    },
    "web19201_payment": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 20,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 90,
      "height": 24,
      "left": 1801,
      "top": 18
    },
    "web19201_platinumhomemortgageWhite": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 41.15,
      "height": 34.55,
      "left": 29,
      "top": 12
    },
    "web19201_component42": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "width": 106,
      "height": 66,
      "left": 736,
      "top": 833
    },
    "web19201_component42_path2": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 106,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component42_buy": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(41, 79, 130, 1)",
      "fontSize": 30,
      "fontWeight": "500",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 58,
      "height": 37,
      "left": 24,
      "top": 15
    },
    "web19201_component52": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "width": 106,
      "height": 66,
      "left": 1126,
      "top": 833
    },
    "web19201_component52_rectangle10": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopWidth": 2,
      "borderTopColor": "rgba(72, 105, 148, 1)",
      "borderRightWidth": 2,
      "borderRightColor": "rgba(72, 105, 148, 1)",
      "borderBottomWidth": 2,
      "borderBottomColor": "rgba(72, 105, 148, 1)",
      "borderLeftWidth": 2,
      "borderLeftColor": "rgba(72, 105, 148, 1)",
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 106,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component52_refi": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(54, 84, 124, 1)",
      "fontSize": 30,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 58,
      "height": 37,
      "left": 24,
      "top": 15
    },
    "web19201_rectangle88": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 1920,
      "height": 1058,
      "left": 0,
      "top": 1035
    },
    "web19201_rectangle89": {
      "opacity": 0.4995479881763458,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 1920,
      "height": 1058,
      "left": 0,
      "top": 1035
    },
    "web19201_weAreNotJustAnotherLender": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 55,
      "fontWeight": "700",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 870,
      "height": 67,
      "left": 888,
      "top": 1567
    },
    "web19201_whatMakesUsDifferent": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 55,
      "fontWeight": "700",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 692,
      "height": 67,
      "left": 171,
      "top": 1833
    },
    "web19201_hereAtPlatinumHomeMortgageWeAreInTheBusinessOfHelpingPeopleOurBeliefIsThatYourHomeIsWhereLoveAndSecurityComesFromWeStriveToGetEveryPersonIntoTheirOwnHomeTalkToOurAmazingTeamTodayToSeeWhatTheyCanDoForYou": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 25,
      "fontWeight": "300",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 873,
      "height": 132,
      "left": 888,
      "top": 1654
    },
    "web19201_workingWithADirectLenderLikePlatinumCanHelpYouAchieveYourHomeownershipGoalsInAMuchSmootherSimplerProcess": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 25,
      "fontWeight": "300",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 717,
      "height": 132,
      "left": 171,
      "top": 1920
    },
    "web19201_line10": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 1591,
      "height": 3,
      "left": 169.5,
      "top": 1799
    },
    "web19201_component618": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 1586,
      "top": 1833
    },
    "web19201_component618_path1e868ca31": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component618_startNowe84ab019": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 30,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 150,
      "height": 37,
      "left": 12,
      "top": 15
    },
    "web19201_rectangle86": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 45,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 45,
      "width": 379,
      "height": 85,
      "left": -1,
      "top": 982
    },
    "web19201_whoWeAre": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 45,
      "fontWeight": "300",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 276,
      "height": 55,
      "left": 40,
      "top": 997
    },
    "web19201_rectangle91": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 1920,
      "height": 1054,
      "left": 1,
      "top": 2106
    },
    "web19201_rectangle92": {
      "opacity": 0.4995479881763458,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 1920,
      "height": 1056,
      "left": 1,
      "top": 2106
    },
    "web19201_rectangle93": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopWidth": 2,
      "borderTopColor": "rgba(54, 85, 124, 1)",
      "borderRightWidth": 2,
      "borderRightColor": "rgba(54, 85, 124, 1)",
      "borderBottomWidth": 2,
      "borderBottomColor": "rgba(54, 85, 124, 1)",
      "borderLeftWidth": 2,
      "borderLeftColor": "rgba(54, 85, 124, 1)",
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "shadowColor": "rgb(0,  0,  0)",
      "shadowOpacity": 0.1607843137254902,
      "shadowOffset": {
        "width": 0,
        "height": 10
      },
      "shadowRadius": 20,
      "width": 483,
      "height": 69,
      "left": 172,
      "top": 2337
    },
    "web19201_rectangle94": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopWidth": 2,
      "borderTopColor": "rgba(54, 85, 124, 1)",
      "borderRightWidth": 2,
      "borderRightColor": "rgba(54, 85, 124, 1)",
      "borderBottomWidth": 2,
      "borderBottomColor": "rgba(54, 85, 124, 1)",
      "borderLeftWidth": 2,
      "borderLeftColor": "rgba(54, 85, 124, 1)",
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "shadowColor": "rgb(0,  0,  0)",
      "shadowOpacity": 0.1607843137254902,
      "shadowOffset": {
        "width": 0,
        "height": 10
      },
      "shadowRadius": 20,
      "width": 483,
      "height": 69,
      "left": 172,
      "top": 2444
    },
    "web19201_rectangle95": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopWidth": 2,
      "borderTopColor": "rgba(54, 85, 124, 1)",
      "borderRightWidth": 2,
      "borderRightColor": "rgba(54, 85, 124, 1)",
      "borderBottomWidth": 2,
      "borderBottomColor": "rgba(54, 85, 124, 1)",
      "borderLeftWidth": 2,
      "borderLeftColor": "rgba(54, 85, 124, 1)",
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "shadowColor": "rgb(0,  0,  0)",
      "shadowOpacity": 0.1607843137254902,
      "shadowOffset": {
        "width": 0,
        "height": 10
      },
      "shadowRadius": 20,
      "width": 483,
      "height": 69,
      "left": 172,
      "top": 2551
    },
    "web19201_component74": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 332,
      "top": 2668
    },
    "web19201_component74_path1f3972f84": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component74_calculate": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(54, 84, 124, 1)",
      "fontSize": 30,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 140,
      "height": 37,
      "left": 17,
      "top": 15
    },
    "web19201_getAPreapproaval": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 50,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 476,
      "height": 61,
      "left": 172,
      "top": 2937
    },
    "web19201_quickLookAtYourMonthlyPayments": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 45,
      "fontWeight": "300",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 836,
      "height": 55,
      "left": 172,
      "top": 2231
    },
    "web19201_aPreapprovalCanGiveYouTheExactAmountYouCanAffordAtNoObligationOrCostToYou": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 25,
      "fontWeight": "300",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 574,
      "height": 68,
      "left": 172,
      "top": 3019
    },
    "web19201_line12": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 1591,
      "height": 3,
      "left": 170.5,
      "top": 2902
    },
    "web19201_howMuchDoYouWantToBorrow": {
      "opacity": 0.7544729709625244,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(41, 79, 130, 1)",
      "fontSize": 25,
      "fontWeight": "300",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 436,
      "height": 30,
      "left": 195,
      "top": 2357
    },
    "web19201_whatIsTheInterestRate": {
      "opacity": 0.7544729709625244,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(41, 79, 130, 1)",
      "fontSize": 25,
      "fontWeight": "300",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 306,
      "height": 30,
      "left": 260,
      "top": 2464
    },
    "web19201_estimatedMonthlyPayment": {
      "opacity": 0.7544729709625244,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(41, 79, 130, 1)",
      "fontSize": 25,
      "fontWeight": "700",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 372,
      "height": 30,
      "left": 232,
      "top": 2791
    },
    "web19201_howManyYearsIsTheLoan": {
      "opacity": 0.7544729709625244,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(41, 79, 130, 1)",
      "fontSize": 25,
      "fontWeight": "300",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 355,
      "height": 30,
      "left": 236,
      "top": 2571
    },
    "web19201_line11": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 483,
      "height": 5,
      "left": 172.5,
      "top": 2834
    },
    "web19201_component619": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 1589,
      "top": 2937
    },
    "web19201_component619_path1f009790d": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component619_startNow012f5e81": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 30,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 150,
      "height": 37,
      "left": 12,
      "top": 15
    },
    "web19201_rectangle90": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(54, 84, 124, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 45,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 45,
      "width": 775,
      "height": 85,
      "left": 0,
      "top": 2050
    },
    "web19201_monthlyPaymentsMadeEasy": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 45,
      "fontWeight": "300",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 664,
      "height": 55,
      "left": 41,
      "top": 2065
    },
    "web19201_rectangle100": {
      "opacity": 0.4995479881763458,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 1920,
      "height": 1025,
      "left": -1,
      "top": 3175
    },
    "web19201_rectangle101": {
      "opacity": 0.6499999761581421,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 512,
      "height": 208,
      "left": 1248,
      "top": 3831
    },
    "web19201_rectangle103": {
      "opacity": 0.6499999761581421,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 512,
      "height": 208,
      "left": 169,
      "top": 3831
    },
    "web19201_rectangle102": {
      "opacity": 0.6499999761581421,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 512,
      "height": 208,
      "left": 708,
      "top": 3831
    },
    "web19201_rectangle104": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 512,
      "height": 375,
      "left": 1248,
      "top": 3467
    },
    "web19201_rectangle105": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 512,
      "height": 375,
      "left": 708,
      "top": 3467
    },
    "web19201_rectangle106": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 512,
      "height": 375,
      "left": 169,
      "top": 3467
    },
    "web19201_component620": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 169,
      "top": 3320
    },
    "web19201_component620_path1eae9680b": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component620_fromCeo": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 25,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 128,
      "height": 30,
      "left": 23,
      "top": 20
    },
    "web19201_component621": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 359,
      "top": 3320
    },
    "web19201_component621_path1b238e024": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component621_holiday": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 25,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 94,
      "height": 30,
      "left": 40,
      "top": 20
    },
    "web19201_component622": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 549,
      "top": 3320
    },
    "web19201_component622_path191e135b0": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component622_market": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 25,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 86,
      "height": 30,
      "left": 44,
      "top": 20
    },
    "web19201_component623": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 739,
      "top": 3320
    },
    "web19201_component623_path11fb01002": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component623_realEstate": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 25,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 140,
      "height": 30,
      "left": 17,
      "top": 20
    },
    "web19201_component624": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 929,
      "top": 3320
    },
    "web19201_component624_path164d77394": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component624_resources": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 25,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 126,
      "height": 30,
      "left": 24,
      "top": 20
    },
    "web19201_component625": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 1119,
      "top": 3320
    },
    "web19201_component625_path1bb7d2e1c": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component625_spotlight": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 25,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 116,
      "height": 30,
      "left": 29,
      "top": 20
    },
    "web19201_component626": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 1309,
      "top": 3320
    },
    "web19201_component626_path189720d44": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component626_technology": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 25,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 143,
      "height": 30,
      "left": 16,
      "top": 20
    },
    "web19201_line13": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 1591,
      "height": 3,
      "left": 168.5,
      "top": 3425
    },
    "web19201_commonMortgageTermsExplained": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(54, 84, 124, 1)",
      "fontSize": 25,
      "fontWeight": "700",
      "fontStyle": "normal",
      "fontFamily": "Helvetica Neue",
      "textAlign": "left",
      "lineHeight": 28,
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 455,
      "height": 42,
      "left": 1270,
      "top": 3850.5
    },
    "web19201_theSpringMarketHasSprung": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(54, 84, 124, 1)",
      "fontSize": 25,
      "fontWeight": "700",
      "fontStyle": "normal",
      "fontFamily": "Helvetica Neue",
      "textAlign": "left",
      "lineHeight": 28,
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 455,
      "height": 42,
      "left": 740,
      "top": 3850.5
    },
    "web19201_theRoaring20sMoneyMachine": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(54, 84, 124, 1)",
      "fontSize": 25,
      "fontWeight": "700",
      "fontStyle": "normal",
      "fontFamily": "Helvetica Neue",
      "textAlign": "left",
      "lineHeight": 28,
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 455,
      "height": 42,
      "left": 201,
      "top": 3850.5
    },
    "web19201_ellipse23": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 61,
      "height": 61,
      "left": 1270,
      "top": 3966
    },
    "web19201_ellipse24": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 61,
      "height": 61,
      "left": 740,
      "top": 3966
    },
    "web19201_ellipse25": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 61,
      "height": 61,
      "left": 201,
      "top": 3966
    },
    "web19201_authorapril192019": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(112, 112, 112, 1)",
      "fontSize": 20,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Helvetica Neue",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 131,
      "height": 49,
      "left": 1345,
      "top": 3972
    },
    "web19201_authorapril242018": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(112, 112, 112, 1)",
      "fontSize": 20,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Helvetica Neue",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 131,
      "height": 49,
      "left": 815,
      "top": 3972
    },
    "web19201_authorjanuary102020": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(112, 112, 112, 1)",
      "fontSize": 20,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Helvetica Neue",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 193,
      "height": 49,
      "left": 276,
      "top": 3972
    },
    "web19201_loremIpsumDolorSitAmetConseteturSadipscingElitrSedDiamNonumyEirmodTemporInviduntUtLaboreEtDoloreMagnaAliquyamEratSedDiamVoluptuaAtVeroEosEtAccusamEtJustoDuoDoloresEtEaRebumStetClitaKasdGubergrenNoSeaTakimata44f534eb": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(54, 84, 124, 1)",
      "fontSize": 15,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 480,
      "height": 77,
      "left": 1270,
      "top": 3883
    },
    "web19201_loremIpsumDolorSitAmetConseteturSadipscingElitrSedDiamNonumyEirmodTemporInviduntUtLaboreEtDoloreMagnaAliquyamEratSedDiamVoluptuaAtVeroEosEtAccusamEtJustoDuoDoloresEtEaRebumStetClitaKasdGubergrenNoSeaTakimata1cc9e289": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(54, 84, 124, 1)",
      "fontSize": 15,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 480,
      "height": 77,
      "left": 740,
      "top": 3883
    },
    "web19201_loremIpsumDolorSitAmetConseteturSadipscingElitrSedDiamNonumyEirmodTemporInviduntUtLaboreEtDoloreMagnaAliquyamEratSedDiamVoluptuaAtVeroEosEtAccusamEtJustoDuoDoloresEtEaRebumStetClitaKasdGubergrenNoSeaTakimata": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(54, 84, 124, 1)",
      "fontSize": 15,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 480,
      "height": 77,
      "left": 201,
      "top": 3883
    },
    "web19201_rectangle96": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(54, 84, 124, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 45,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 45,
      "width": 630,
      "height": 85,
      "left": 1,
      "top": 3119
    },
    "web19201_aFreshLookAtYourHome": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 45,
      "fontWeight": "300",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 572,
      "height": 55,
      "left": 16,
      "top": 3134
    },
    "web19201_rectangle110": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 1920,
      "height": 1025,
      "left": -3,
      "top": 4215
    },
    "web19201_rectangle113": {
      "opacity": 0.4995479881763458,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 1920,
      "height": 880,
      "left": -3,
      "top": 4215
    },
    "web19201_foundThePerfectHomeOrInTheHomeYouLove": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 50,
      "fontWeight": "700",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 634,
      "height": 122,
      "left": 167,
      "top": 4945
    },
    "web19201_line15": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 1591,
      "height": 3,
      "left": 166.5,
      "top": 4910
    },
    "web19201_component627": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 1583,
      "top": 4945
    },
    "web19201_component627_path1": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 175,
      "height": 66,
      "left": 0,
      "top": 0
    },
    "web19201_component627_startNow": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 30,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "center",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 150,
      "height": 37,
      "left": 12,
      "top": 15
    },
    "web19201_rectangle114": {
      "opacity": 0.8500000238418579,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopLeftRadius": 50,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 50,
      "width": 1065,
      "height": 544,
      "left": 168,
      "top": 4297
    },
    "web19201_andyWentOverAndAboveToMakeSureThatWeHadTheBestPossibleExperienceWithOurMortgageFromTheMomentWeStartedWorkingWithHimHeWasInConstantContactEnsuringThatWeHadTheBestRateAndAnsweringAnyAndAllQuestionsWeCouldThrowH": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(54, 84, 124, 1)",
      "fontSize": 30,
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 901,
      "height": 360,
      "left": 249,
      "top": 4368
    },
    "web19201_group6": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 163,
      "height": 17,
      "left": 578,
      "top": 4802
    },
    "web19201_group6_ellipse15": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 19,
      "height": 19,
      "left": -1,
      "top": -1
    },
    "web19201_group6_ellipse16": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 19,
      "height": 19,
      "left": 34,
      "top": -1
    },
    "web19201_group6_ellipse17": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 19,
      "height": 19,
      "left": 72,
      "top": -1
    },
    "web19201_group6_ellipse18": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 19,
      "height": 19,
      "left": 109,
      "top": -1
    },
    "web19201_group6_ellipse19": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 20,
      "height": 19,
      "left": 144,
      "top": -1
    },
    "web19201_rectangle109": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(54, 84, 124, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopWidth": 1,
      "borderTopColor": "rgba(0, 0, 0, 0)",
      "borderRightWidth": 1,
      "borderRightColor": "rgba(0, 0, 0, 0)",
      "borderBottomWidth": 1,
      "borderBottomColor": "rgba(0, 0, 0, 0)",
      "borderLeftWidth": 1,
      "borderLeftColor": "rgba(0, 0, 0, 0)",
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 1918.87,
      "height": 199,
      "left": -3.5,
      "top": 5094.5
    },
    "web19201_group5": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "transparent",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 163.91,
      "height": 32.81,
      "left": 847,
      "top": 5136
    },
    "web19201_group5_rectangle64": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 34.16,
      "height": 23.5,
      "left": -0.5,
      "top": 3.5
    },
    "web19201_group5_rectangle65": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 29.47,
      "height": 31.81,
      "left": 65.5,
      "top": -0.5
    },
    "web19201_group5_rectangle66": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 35.91,
      "height": 28.75,
      "left": 126.5,
      "top": 0.5
    },
    "web19201_homeBlogContactLocationsCareersPayment": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 20,
      "fontFamily": "Montserrat-Regular",
      "textAlign": "left",
      "lineHeight": 29,
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 531,
      "height": 33,
      "left": 177,
      "top": 5140.45
    },
    "web19201_nmlsPrivacyPolicyTermsOfUseDisclosureLicensing": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 20,
      "fontFamily": "Montserrat-Regular",
      "textAlign": "left",
      "lineHeight": 29,
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 587,
      "height": 33,
      "left": 1150,
      "top": 5142.45
    },
    "web19201_x2021PlatinumHomeMortgageCorporationAllRightsReservedLegalLicensingPrivacyInNewYorkDbaPhmcMortgageNmlsId": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 15,
      "fontFamily": "Montserrat-Regular",
      "textAlign": "center",
      "lineHeight": 18,
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 1559,
      "height": 48,
      "left": 177,
      "top": 5222.5
    },
    "web19201_rectangle111": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 53.3,
      "height": 54.61,
      "left": 1774.86,
      "top": 5165.44
    },
    "web19201_rectangle112": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 34.17,
      "height": 55.95,
      "left": 1848.43,
      "top": 5164.53
    },
    "web19201_line14": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 1560,
      "height": 1,
      "left": 176.5,
      "top": 5195
    },
    "web19201_rectangle115": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 45,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 45,
      "width": 157,
      "height": 85,
      "left": -3,
      "top": 5153
    },
    "web19201_platinumlogohorizontal": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 134,
      "height": 46,
      "left": 5,
      "top": 5173
    },
    "web19201_rectangle107": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(54, 84, 124, 1)",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 45,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 45,
      "width": 596,
      "height": 85,
      "left": -1,
      "top": 4157
    },  
    "web19201_rectangle85": {
      "opacity": 1,
      "position": "absolute",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "borderTopLeftRadius": 0,
      "borderTopRightRadius": 0,
      "borderBottomLeftRadius": 0,
      "borderBottomRightRadius": 0,
      "width": 232.15,
      "height": 30.07,
      "left": 121.35,
      "top": 14.28
    },
    "web19201_whatPeopleAreSaying": {
      "opacity": 1,
      "position": "absolute",
      "backgroundColor": "rgba(255, 255, 255, 0)",
      "color": "rgba(255, 255, 255, 1)",
      "fontSize": 45,
      "fontWeight": "300",
      "fontStyle": "normal",
      "fontFamily": "Montserrat",
      "textAlign": "left",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0,
      "width": 521,
      "height": 55,
      "left": 34,
      "top": 4172
    }
};
  